### ISSUE TITLE
Error initializing model in demo notebook

### ISSUE THREAD

**Issue by margaretmeehan** [booknlp/booknlp#17]
Hello! When initializing the BookNLP model in Google Colab, this error occurs:

```RuntimeError: Error(s) in loading state_dict for Tagger: Unexpected key(s) in state_dict: "bert.embeddings.position_ids". ```

It may be a dependency error with the transformers library? I did not get this error when running the notebook in the same environment a month or so ago. Thanks for help. 

<img width="884" alt="Screen Shot 2023-08-27 at 7 46 12 PM" src="https://github.com/booknlp/booknlp/assets/8159064/1c299952-eb5e-4213-a63a-43eb349745b1">

**Comment by dbamman** [comment]
Yes, this looks to be a change in the transformers library; until we update the booknlp code, I've clarified the transformers version should be <= 4.30 in setup.py.  This notebook (and `pip install booknlp` generally) should now work.
