### ISSUE TITLE
What does the number before coherence mean?

### ISSUE THREAD

**Issue by fishfree** [booknlp/booknlp#20]
![71184230074c6325056cc5c5e0967ee](https://github.com/booknlp/booknlp/assets/1741341/b8d39f70-a68f-4680-9de0-5424dd5bd969)
Or the question is what's coding rule of these numbers?

**Comment by DrewThomasson** [comment]
I think it's character id?

**Comment by fishfree** [comment]
I thinks so, but no prooves, i.e. no data source.

**Comment by DrewThomasson** [comment]
It is the quote you can prove it with this code:

import json

with open ("Book.book", "r") as f:
	book_data = json.load(f)

book_data["characters"][0]["id"]

#Will get that characters id
of character at characters index 0 

book_data["characters"][0]["mentions"]["proper"]

#Will get the names used to refer to the character at characters index 0


The character id matches up with the names used to described that character. 

Check the html file and you'll see that all the numbers in the little pink-ish text are the characters id


It's all in the BOOKNLP guide: https://booknlp.pythonhumanities.com/03_files.html

**Comment by fishfree** [comment]
@DrewThomasson Thank you very much!
