### ISSUE TITLE
Get non-quotes

### ISSUE THREAD

**Issue by fakerybakery** [booknlp/booknlp#21]
Hi,
I saw BookNLP can extract quotes, is there any way to extract non-quotes?
For example:
```
SPEAKER 1: "Test"
NARRATOR: Non-qoute
SPEAKER 2: "Test"
```
Thank you!

**Comment by DrewThomasson** [comment]
Lol no BUT actually I made my program do just that by grabbing everything in-between quotes as non quotes, I'll send the code to you when free it outputs quotes.csv and nonquotes.csv files and then a book.csv file that merges them

**Comment by DrewThomasson** [comment]
Never mind now you can just pull the code from my run_gui.py that does just that from my VoxNovel repository

**Comment by fakerybakery** [comment]
Thanks!
